### ISSUE TITLE
Server shuts down, how detect on client

### ISSUE THREAD

**Issue by RobertoSnap** [lucaspoffo/renet#3] opened 2022-01-19 13:19 UTC
When server shuts down for whatever reason, how can a client detect that?

If not implemented, could you give me som pointers and il try to create a pr.

**Comment by lucaspoffo** [comment] 2022-01-21 17:11
If a server shuts down, the client will detect it by timeout since it will stop sending messages to all clients.
If you want to close the server manually, you could use the `server.disconnect_clients` to disconnect all connected clients before closing the server.

What is the expected behavior you want? Or if you could describe your scenario, we can define better what should happen ;)

**Comment by RobertoSnap** [comment] 2022-01-22 19:08
ohh, its just that when i stop the server, clients are not notified and still think they are connected.

Say i run a client and server in a workspace, then i stop the server.

In a system on the client i run ` client.is_connected()`  each sec which always resolves to true even though i shut down the server.

But maybe i need to do more explicit update on the client? My current update function is only

```rs
   if !timer.0.tick(time.delta()).just_finished() {
        return;
    }
    client
        .update(Duration::from_secs_f64(time.delta_seconds_f64()))
        .expect("Could not update server");

    while let Some(text) = client.receive_message(Channels::Reliable as u8) {
        let decoded: ServerMessage =
            bincode::deserialize(&text[..]).expect("Could not decode client message");
        // println!("Client recv: {:?}", decoded);
        server_message_event_writer.send(decoded);
    }

    client
        .send_packets()
        .expect("Could not send packets from client.");
        ```

**Comment by lucaspoffo** [comment] 2022-01-23 14:45
The update loop seems right, it should panic after 5 seconds the server shuts down, the default timeout duration. The problem might be somewhere else, maybe it's not calling the update or the delta time is not right.
The code I use in the demo is:
```rust
            if let Err(e) = chat_client.update(duration) {
                error!("{}", e);
            }
            if let Some(e) = chat_client.disconnected() {
                self.state = AppState::Start;
                self.connection_error = Some(Box::new(RenetError::ClientDisconnected(e)));
                self.connected_server_addr = None;
                self.chat_server = None;
                self.client = None;
             } else {
                // Message Logic
                if let Err(e) = chat_client.send_packets() {
                    error!("Error sending packets: {}", e);
                }
             }
```
 Pretty similar. I just handle the error instead of panicking, and I get the timeout after 5 seconds.

**Comment by lucaspoffo** [comment] 2022-05-12 19:18
With the 70321926f88f665fbf93ef220754706a367db270, the server should send the disconnect packets when at the time of the call. Before, you would need to wait for one frame for the disconnect packets to be sent.

You can check out the `chat_demo` to see this working. When the host selects the exit button it calls the disconnect clients, and all connected clients are notified correctly.

**Closed by lucaspoffo** 2022-05-12 19:18 UTC
